### ISSUE TITLE
parameter output truncated at six significant figures

### ISSUE THREAD

**Issue by kostrzewa** [sunpho84/nissa#3]
startup parameter output seems to be performed with default float width which generally corresponds to six significant figures. As a result, (see @marcogarofalo's job), the output for ```Kappa```, for example, is misleading.

**Comment by sunpho84** [comment]
I've modififed %lg into %.16lg in src/ios/input.cpp  in commit 17023618abb2f56e508efb6bf6bdc0e87e47aba7
@Marcogarofalo can take the bin in 

/marconi/home/userexternal/fsanfili/programs/nissa/build_DD_KNL/bin/ib

**Comment by kostrzewa** [comment]
cheers!
