### ISSUE TITLE
Clarifying the PAR logic

### ISSUE THREAD

**Issue by sunpho84** [sunpho84/nissa#40]
The PAR macro at the moment is an alias for DEFAULT_PARALLEL_LOOP

https://github.com/sunpho84/nissa/blob/c3d3d9d212cd86b93f14d51a7e2a4173d53d7287/src/threads/threads.hpp#L137

This was a quick "hack" I've made when implementing `Field` (first versions), and the whole codebase uses this feature to instantiate the parallel loops explicitly. In the logic of the Field2 and all the metaprogrammed evaluation of expressions, this is too limited as the `Field2` come with a memory type associated: https://github.com/sunpho84/nissa/blob/c3d3d9d212cd86b93f14d51a7e2a4173d53d7287/src/expr/fieldDeclaration.hpp#L30 

Therefore the parallel loop, which is implicitly instantiated when the assignment to the `Field2` is carried out, must proceed after testing the appropriate execution space, as indeed is done in https://github.com/sunpho84/nissa/blob/c3d3d9d212cd86b93f14d51a7e2a4173d53d7287/src/expr/field.hpp#L105-L134

This should be generalized as assignment of `Field2` is not the only case in which a loop must be issued. A possibility would be to declare a specific component as parallelizable, and intercept all loops over such a component when spawning `compsLoop` https://github.com/sunpho84/nissa/blob/c3d3d9d212cd86b93f14d51a7e2a4173d53d7287/src/expr/comps.hpp#L97-L168 
however this would require to guess the appropriate execution space for the loop, which is a nontrivial task.

Plus I'm not confident that this is a good solution, as in any case this is not going to address a number of corner cases on where the parallel loop must be issued, which one would need to address explicitly. By the time, I would keep the instantiation of the parallel loop explicit, recurring to a modification of https://github.com/sunpho84/nissa/blob/c3d3d9d212cd86b93f14d51a7e2a4173d53d7287/src/expr/field.hpp#L105 in which the macro get an argument specifying which of the two loop has to be actually instantiated, as in

```
PARALLEL_LOOP(CONDITION,
{
})
```
Where the condition is some external `constexpr`.

Unfortunately, doubling the code is the only solution that I've found, as the lambda function must be properly decorated to be executed on the device and:
- decorating with `__host__` `__device__` has a [large overhead ](https://stackoverflow.com/questions/70845729/calling-host-device-function-inside-global-function-causing-an-overh)
- decorating cannot be done conditionally, as `__host__` and `__device__` are attribute that are attached at a compilation stage in which the `C++` code seems not to have already been parsed
- scratching my head hard, I could not find a way through

**Comment by joek93** [comment]
This looks like a case-by-case problem. It is a very long shot, but the only solution I can think of is to make a first probe execution where the timings for the different versions are considered and the best is chosen and saved in a cache file, which is then read for the second and real execution. It seems a bit overcomplicated though.

**Comment by sunpho84** [comment]
In a general scenario I agree that one might want to compare execution times on the host and on the device, and choose it appropriately. In general this would give a very flexible code which has the ability to run automatically part of the code on the host, and part on the device. I think this is however quite a long shot, and will require as a first step the implementation of an auto-tuner, which in turn needs to implement a mechanism to dry-eval the expressions. 

For the time being, I would keep the decision of where to execute the code as a specification of the expression itself, which means in practice that if a `Field2` stores data on the device, it will run on device, and in the host otherwise. The storage in turn will default to device if a device is available, with very specific portions of the code to be run on the host, such as load/save a configuration.

**Comment by sunpho84** [comment]
Fixed by 46d906295c25ed4d890c84865c7da6c19235bccb
